{
  "hash": "3039ea3f6e768211202a7637f57fc074",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 05: What makes an estimate the best one?\"\nsubtitle: \"An introduction to ggplot2\"\nexecute:\n  eval: false\n  echo: true\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-copy: true\neditor:\n  markdown:\n    wrap: 72\n---\n\n::: callout-important\n## Due date\n\nThis lab is due **today, by the end of class**. Commit and push your\n`lab-05.qmd` and rendered PDF to your own lab repo, and submit that PDF\non Gradescope.\n:::\n\n# Introduction\n\nEveryone before Gauss worked forwards: *assume the errors look like\nthis, therefore the best estimate is that.* In 1809 Gauss ran the\nargument **backwards**. He assumed the answer — everybody already\naverages their measurements, so take it as given that the average is the\nmost probable value — and asked what the error curve would have to look\nlike for that to be true.\n\nOut came the normal curve. And because the normal curve makes least\nsquares the right thing to do, Gauss had justified least squares.\n\nToday you will build, from scratch, a thing that decides. Given five\nmeasurements and a candidate for the truth, you will write code that\nscores how badly that candidate fits — and then score every candidate\nand take the winner.\n\nDo it one way and the winner is the **mean**. Change a single line and\nthe winner is the **median**. Change another and it is the **midrange**.\nThree defensible rules, three different answers, one set of numbers.\nThat is the argument Legendre, Gauss and Laplace were having, and you\nwill have finished it by the middle of class.\n\n## Learning goals\n\nBy the end of this lab you will be able to:\n\n- tell **random error** from **systematic error**, and say which one\n  averaging fixes;\n- build a plot one layer at a time with `ggplot()`, `aes()`, and a\n  `geom_`, and look the rest up on a cheatsheet;\n- write your own function, and call it from a **loop**;\n- explain why errors must lose their signs before they can be added;\n- score every candidate on a grid and find the best one with\n  `which.min()`;\n- show that minimizing squared errors gives the mean, absolute errors\n  the median, and the worst error the midrange;\n- read an estimate against its own uncertainty, and say when an effect\n  is too small for the data to see.\n\n# Opening activity — how wrong is a room full of people?\n\n**Laptops closed.** Everyone needs a scrap of paper.\n\n## Round 1 — one guess, on your own\n\n**Write down your\nbest guess at Kat's age.** One number. No conferring, no\nranges. Write it down on the small piece of paper.\n\nThat number is a **measurement**. You are the instrument, her age is the\nquantity being measured, and your guess might be wrong by some\namount. \n\n## Round 2 — put the whole class on one chart\n\nYour instructor has written a column of ages down the side of the board,\none per row, and each group has a **different colored marker**.\n\n**Go up and draw one tally mark, in your group's color, on the row for\nyour guess.** \n\nNow, in your group, compute two summaries of your four guesses by hand:\n\n| Summary | How to get it |\n|---|---|\n| Mean | add the four, divide by four |\n| Median | the average of the middle two, in order |\n\nThen **send someone up to write your group's letter, in your color, in\nthe \"group means\" column** to the right of the tallies, on the row\nclosest to your group's mean.\n\n## Round 3 — read the chart\n\nWith your group:\n\n1. **Find your own color.** How many rows do your group's four marks\n   spread across? Now find your group's letter. Is it inside that span,\n   or outside it?\n\n2. **Now look at the four letters together.** How many rows do *they*\n   spread across, compared with the tally marks? Is any letter out at\n   the top or bottom rows where the most extreme marks are?\n\n3. Suppose you had to bet. Would you rather bet on **one tally mark\n   picked at random**, or on **one group letter picked at random**? Say\n   why, using the chart rather than any formula.\n\n4. Did your group's mean and median come out the same, or different? If\n   they differ, which of your four guesses is responsible, and which of\n   the two summaries moved?\n\n::: callout-note\n## What the chart does and does not show\n\nThe tally marks reach across more rows than the letters partly for a\nboring reason: there are sixteen marks and only four letters, and more\nnumbers reach further simply by being more numerous. \n\nRead the **positions** instead. The letters cluster toward the middle,\nand none of them is out at the ends where the more extreme marks are. That\nis the real effect and it is not an artifact of counting: an average of\nfour people is much harder to drag to an extreme than any one person is.\n:::\n\n## Round 4 — one bit of information\n\nYour instructor is **not** going to tell you the answer. She will tell\nyou one thing only: whether the class **over**estimated or\n**under**estimated.\n\n5. Before she says it — look at your chart and try to work it out.\n   Can you? Is there anything in those sixteen numbers that points one\n   way rather than the other?\n\n6. Now she says it. **Did anything on the board predict that?** You have\n   a picture of how much the room disagrees with itself. Does it tell\n   you how wrong the room is?\n\n7. Knowing the direction, can you now correct your group's estimate?\n   What would you still need in order to do it?\n\n8. If nearly everyone leaned the same way, is that the kind of error\n   that **averaging more people** would fix? Would sixteen more students\n   have helped?\n\n::: callout-tip\n## Two kinds of wrong\n\nYour four guesses scattered around your group's own center, and the four\ngroup letters scattered less. That is **random error**, and averaging is\nexactly the right tool for it: more guesses, tighter center, and the\n$1/\\sqrt{n}$ shrinkage you met in lecture.\n\nBut if the whole room leans the same way — everybody reads a face as\nyounger than it is, everybody underestimates a long distance — that is\n**systematic error**, and averaging does nothing to it whatsoever.\nSixteen people making the same mistake is still that mistake, reported\nwith more confidence. A hundred would be worse: the same wrong answer,\nnow with a tighter spread around it to make it look trustworthy.\n:::\n\n\n## Now open your laptops — Getting your repo\n\nFind your repo beginning with `lab-05` in the\n[statistical-history organization](https://github.com/statistical-history).\nClone it in RStudio using **File → New Project → Version Control → Git**\nand its SSH address. If you have already cloned it, open that project\nand **Pull**.\n\nOpen `lab-05.qmd`, enter your name and group, and render once. You\nshould also see a `data/` folder, which you will need in Part 4.\nKeep these instructions beside your working document.\n\n## The question this lab is about\n\nYour group produced two summaries of one set of guesses (mean and median), and they\nprobably do not agree with each other.\n\n> **Prediction 1.** If you had to report a single number, should it be\n> the mean or the median? Vote in your group and record the count.\n\n> **Prediction 2.** In a moment you will write code that scores how\n> badly a guess fits. **If we change the rule for what counts as\n> \"badly,\" will the best guess change** — or is the best guess simply\n> the best guess?\n\n\n# Part 1 — Record the board\n\nRecord your group's vote on Prediction 1 and your answer to Prediction 2.\n\n# Part 2 — Scoring a guess\n\nYour group voted on whether to report the mean or the median. Now we\nsettle it — not by opinion, but by building something that can decide.\n\n## The measurements\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   4.0.3     ✔ tibble    3.2.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.0.4     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n:::\n\n\n`library(tidyverse)` loads **dplyr**, which you used last week, and also\n**ggplot2**, which is today's tool. You do not need a separate\n`library(ggplot2)`.\n\nPut the age guesses aside and take a smaller set of numbers, where the\ndisagreement is sharper: **five readings of the same quantity, made with\nthe same instrument on the same afternoon.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeasurements <- tibble(\n  reading = 1:5,\n  value = c(9.8, 10.0, 10.2, 13.9, 14.1)\n)\nmeasurements\n```\n:::\n\n\nThree agree with each other and two do not, and nobody wrote down which\ntwo were the mistake. Your group's guesses probably had the same shape:\na cluster, and one or two people well outside it.\n\n## A plot is built from layers\n\nLast week you read a pipeline as a sentence: *take this data, then\nfilter it, then count it.* A ggplot reads the same way, except the steps\njoin with `+` instead of `|>`, and each step adds a layer to a picture\nrather than changing a table.\n\nEvery plot needs three things: **the data**, an **aesthetic mapping**\nsaying which column becomes which visual property, and at least one\n**geom** saying what marks get drawn. Run these three chunks separately\nand watch each one arrive.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = measurements)\n```\n:::\n\n\nAn empty grey rectangle. You said which table to draw from and nothing\nelse, so nothing was drawn.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = measurements, mapping = aes(x = reading, y = value))\n```\n:::\n\n\nNow there are axes with names and a scale. `aes()` is the **aesthetic\nmapping**: *put `reading` along the bottom and `value` up the side*. R\nnow knows how far across and how far up any mark would go. It still has\nnot been told to draw one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = measurements, mapping = aes(x = reading, y = value)) +\n  geom_point(size = 3)\n```\n:::\n\n\n`geom_point()` draws one dot per row. **The `+` goes at the end of a\nline, never the start of the next one** — that is the most common ggplot\nerror and R reports it as an unhelpful \"object not found\".\n\n`size = 3` sits **outside** `aes()`, because it is one fixed value\nrather than something looked up per row.\n\n**2.1** How many dots appeared, and what does one dot represent? Which\ncolumn controls how far up a dot sits?\n\n::: callout-tip\n## Where to look things up\n\nYou are not expected to memorize geoms. Keep the\n[ggplot2 cheatsheet](https://rstudio.github.io/cheatsheets/data-visualization.pdf)\nopen in a tab — one page of geoms, one page of everything else — and\nreach for it whenever a plot needs something you have not seen.\n\nToday uses six: `geom_point()`, `geom_line()`, `geom_hline()`,\n`geom_vline()`, `geom_abline()` and `geom_boxplot()`. The sheet lists\nabout forty more. It also shows the pairs that are easy to confuse —\n`geom_line()` joins points in order of **x**, while `geom_path()` joins\nthem in the order the **rows** appear, which matters the moment your x\naxis is not what orders the data.\n:::\n\n## Drawing a guess\n\nA guess at the true value is a horizontal line. `geom_hline()` adds one,\nand `labs()` sets the text:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(measurements, aes(x = reading, y = value)) +\n  geom_point(size = 3) +\n  geom_hline(yintercept = 10, linetype = \"dashed\") +\n  labs(\n    x = \"reading number\",\n    y = \"measured value\",\n    title = \"Five measurements, and a guess of 10\"\n  )\n```\n:::\n\n\nLayers stack in the order you write them, so the line is drawn over the\npoints.\n\n**2.2** Change `yintercept` to 12 and render again. Which guess looks\nbetter to you — 10, or 12? Write down your answer and one sentence\nsaying what \"better\" meant when you decided.\n\n## The errors\n\nA guess is wrong by a different amount for each reading. Those amounts\nare the **errors** — on the plot, the vertical distances from each dot\nto the dashed line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- measurements$value\n\nerrors <- x - 10\nerrors\n```\n:::\n\n\n**2.3** Which two errors are large, and why? Look back at the plot and\nsay which dots they belong to.\n\n::: callout-tip\n## Two ways to stop the errors cancelling\n\nWe want a **single number** saying how badly a guess fits, so that any\ntwo guesses can be compared. The five errors have to be combined into\none.\n\nThey cannot simply be added, because they carry signs: an error of $-4$\nand an error of $+4$ would cancel to nothing, exactly like two errors of\nzero. Whatever we do, every error has to count as positive no matter\nwhich side of the line it fell on. There are two obvious ways to arrange\nthat:\n\n- **square** each error, or\n- take its **absolute value**.\n\nBoth are reasonable. We will square first, in the rest of\nPart 2, and take absolute values in Part 3.\n:::\n\n## One guess, one number\n\nSquare the errors and add them up. That single number says how badly a\nguess fits, with no cancellation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nerrors^2\nsum(errors^2)\n```\n:::\n\n\n**2.4** Do the same for a guess of 12, one line at a time, and say which\nof the two guesses scores lower. Does it agree with what you decided in\n2.2?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YOUR CODE HERE\n```\n:::\n\n\n## Write it once, use it many times\n\nRather than retyping that for every guess, wrap it in a function of your\nown:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsquared_error <- function(guess) {\n  errors <- x - guess\n  sum(errors^2)\n}\n\nsquared_error(10)\nsquared_error(12)\n```\n:::\n\n\n`function(guess)` says the recipe takes one input, which it calls\n`guess`. Everything between the braces is the recipe. The last line\ninside is what comes back out.\n\n**2.5** Call your function on a guess of 11.6. Is the score lower than\nboth of the previous two?\n\n## Every guess, not just three\n\nNow make a long list of candidate guesses and score all of them with a\n**loop**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- seq(8, 16, by = 0.05)\nlength(grid)\n```\n:::\n\n\n`seq()` builds a regular sequence: 161 candidate values from 8 to 16,\na twentieth apart.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscore <- numeric(length(grid))\n\nfor (i in seq_along(grid)) {\n  score[i] <- squared_error(grid[i])\n}\n\nhead(score)\n```\n:::\n\n\nRead it line by line:\n\n- `numeric(length(grid))` makes an empty container of the right size,\n  one slot per candidate.\n- `for (i in seq_along(grid))` runs the body once for each position in\n  `grid`, with `i` taking the values 1, 2, 3, and so on.\n- `score[i] <- squared_error(grid[i])` scores candidate number `i` and\n  files the answer in slot `i`.\n\n**This is the new R tool today: a loop.** Everything before this has\nhappened to whole vectors at once.\n\n## Plot the scores\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscores <- tibble(guess = grid, score = score)\n\nggplot(scores, aes(x = guess, y = score)) +\n  geom_line() +\n  labs(\n    x = \"candidate value\",\n    y = \"sum of squared errors\",\n    title = \"How badly each candidate fits the five measurements\"\n  )\n```\n:::\n\n\n`geom_line()` joins the rows in order along the x axis, which is what\nyou want for a curve. `geom_point()` here would draw 161 dots.\n\n**2.6** Describe the curve in one sentence. Where is it lowest, roughly?\n\n## Find the bottom\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid[which.min(score)]\nmean(x)\n```\n:::\n\n\n`which.min()` returns the **position** of the smallest value, not the\nvalue itself; `grid[...]` then looks up the candidate sitting in that\nposition.\n\n**2.7** Compare the two numbers. Then compare them with your group's\nvote on Prediction 1.\n\n::: callout-note\n## What you just found\n\nOf every candidate between 8 and 16, the one with the smallest sum of\nsquared errors is the **arithmetic mean** — not approximately, exactly.\n\nThat is not a coincidence and it is not about this data. It is true for\nany set of numbers, and it is the reason least squares and the average\nare connected at all. Legendre published the rule \"minimize the sum of\nsquared errors\" in 1805 without proving anything about it; Gauss showed\nin 1809 what follows from it.\n\nYou found it in four lines and a loop.\n:::\n\n::: callout-warning\n## Render, commit, and push\n\nRender your document, then commit and push before moving on.\n:::\n\n# Part 3 — Change the rule, change the answer\n\nSquaring was a choice. Part 2 offered two ways to stop the errors\ncancelling — **square** each one, or take its **absolute value** — and\nyou squared. Now take the other one and see what it gives you.\n\n## Absolute errors instead of squared ones\n\nThe tool you need is `abs()`, which takes the **absolute value** of each\nnumber — it throws away the minus sign and leaves everything else alone:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabs(c(-3, 2, -0.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.0 2.0 0.5\n```\n\n\n:::\n:::\n\n\n**3.1** Now write the second scoring function yourself. Call it\n`absolute_error`, give it one input called `guess`, and inside it do the\nsame two steps as `squared_error` did — find the errors, then combine\nthem into one number — except that this time you take absolute values\ninstead of squaring.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabsolute_error <- function(guess) {\n  # YOUR CODE HERE -- two lines, modelled on squared_error()\n}\n```\n:::\n\n\nTest it on the same two guesses you used before:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabsolute_error(10)\nabsolute_error(11.6)\n```\n:::\n\n\n**3.2** Which of those two guesses scores lower under this rule? Under\nthe squared rule in Part 2, which scored lower? Do the two rules agree?\n\n## Score every guess again\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscore_abs <- numeric(length(grid))\n\nfor (i in seq_along(grid)) {\n  score_abs[i] <- absolute_error(grid[i])\n}\n\nggplot(tibble(guess = grid, score = score_abs),\n       aes(x = guess, y = score)) +\n  geom_line() +\n  labs(\n    x = \"candidate value\",\n    y = \"sum of absolute errors\",\n    title = \"The same candidates, scored a different way\"\n  )\n```\n:::\n\n\n**3.3** Find the bottom of this curve, then compare it with the **mean**\nand the **median** of the five readings. Which one has the rule picked\nout this time?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YOUR CODE HERE -- adapt the two lines from 2.7\n```\n:::\n\n\n**3.4** The curve in Part 2 was a smooth bowl. This one is made of\nstraight pieces joined at corners — and you can probably see two of\nthem, one near 10 and one near 14. **There are actually five.**\n\nAdd a layer marking each reading to find them. `geom_vline()` is the\nvertical twin of the `geom_hline()` you used in Part 2:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tibble(guess = grid, score = score_abs),\n       aes(x = guess, y = score)) +\n  geom_line() +\n  geom_vline(xintercept = x, linetype = \"dotted\", color = \"firebrick\") +\n  labs(x = \"candidate value\", y = \"sum of absolute errors\",\n       title = \"Corners, and the five readings\")\n```\n:::\n\n\nWhere are the five corners? Why do only two of them stand out? And what\nchanges about the curve as the candidate crosses a reading?\n\n## One more rule\n\nHere is a third, just as defensible: never mind the total, **make the\nworst error as small as possible.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworst_error <- function(guess) {\n  errors <- x - guess\n  max(abs(errors))\n}\n\nscore_worst <- numeric(length(grid))\n\nfor (i in seq_along(grid)) {\n  score_worst[i] <- worst_error(grid[i])\n}\n\ngrid[which.min(score_worst)]\n(min(x) + max(x)) / 2\n```\n:::\n\n\nOnly `sum` became `max`.\n\n**3.5** What summary did this rule pick out? It is the **midrange**,\nhalfway between the smallest and largest reading — a summary that\nignores everything in between.\n\n## The board\n\n**3.6** Fill this in from your own results. Everyone has all three.\n\n| Rule | Where it bottoms out | Which summary |\n|---|---|---|\n| Smallest sum of **squared** errors | | |\n| Smallest sum of **absolute** errors | | |\n| Smallest **worst** error | | |\n\n**3.7** Three reasonable rules, three different answers, one set of five\nnumbers. Now settle **Prediction 2**: was \"which single number should\nwe report\" answerable as you were given it? Name the one thing that was\nmissing, and say who supplies it — the data, or the person doing the\nanalysis.\n\n\n::: callout-warning\n## Render, commit, and push\n\nRender your document, then commit and push before moving on.\n:::\n\n# Part 4 — When is a number a new piece of information?\n\nThe last dataset is real. For eleven years the barometer at the Paris\nObservatory was read four times a day — 9 a.m., noon, 3 p.m. and\n9 p.m. — and the readings were published.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregister <- read_csv(\"data/paris_register.csv\", show_col_types = FALSE)\nglimpse(register)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,978\nColumns: 8\n$ date    <date> 1816-01-01, 1816-01-02, 1816-01-03, 1816-01-04, 1816-01-05, 1…\n$ year    <dbl> 1816, 1816, 1816, 1816, 1816, 1816, 1816, 1816, 1816, 1816, 18…\n$ month   <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…\n$ day     <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,…\n$ mm_9am  <dbl> 778.04, 771.52, 768.59, 776.09, 772.87, 768.59, 761.69, 765.22…\n$ mm_noon <dbl> 776.62, 770.02, 768.22, 776.02, 771.67, 765.22, 762.74, 762.59…\n$ mm_3pm  <dbl> 775.79, 769.12, 768.37, 775.72, 771.07, 762.51, 763.71, 760.04…\n$ mm_9pm  <dbl> 775.12, 768.29, 771.52, 776.02, 771.14, 761.09, 765.52, 757.64…\n```\n\n\n:::\n:::\n\n\n| Column | Meaning |\n|---|---|\n| `date`, `year`, `month`, `day` | The day of the reading |\n| `mm_9am`, `mm_noon`, `mm_3pm`, `mm_9pm` | Barometer height at each hour, in millimetres |\n\nNearly four thousand days, four readings each: about **sixteen thousand\nnumbers**. Laplace used this register to look for a very small effect,\nand sixteen thousand observations sounds like plenty.\n\nThe question for this part is whether sixteen thousand numbers are\nsixteen thousand pieces of information.\n\n## 4.1 — Getting the data into the right shape\n\nBefore plotting anything, pull out the month of April in 1820 and the three daytime\nreadings:\n\n\n::: {.cell}\n\n```{.r .cell-code}\napril <- register |>\n  filter(year == 1820, month == 4) |>\n  select(date, mm_9am, mm_noon, mm_3pm)\nhead(april)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  date       mm_9am mm_noon mm_3pm\n  <date>      <dbl>   <dbl>  <dbl>\n1 1820-04-01   769.    769.   768.\n2 1820-04-02   770.    770.   768.\n3 1820-04-03   769.    768.   768.\n4 1820-04-04   764.    762.   760.\n5 1820-04-05   760.    759.   758.\n6 1820-04-06   754.    753.   752.\n```\n\n\n:::\n:::\n\n\nThis dataset has one row per day, three readings sitting side by side across the row.\nThat is a perfectly good shape for reading with your eyes, and the wrong\nshape for ggplot.\n\nYou want **one line per reading**, and ggplot draws one line per *group* — so it has to be able to find the\nreading as **a column it can map**. Right now \"which reading\" is not\nrecorded in any column; it is recorded in the column *names*. ggplot\ncannot map a column name.\n\n`pivot_longer()` fixes that by stacking the three columns into one:\n\n\n::: {.cell}\n\n```{.r .cell-code}\napril_long <- april |>\n  pivot_longer(c(mm_9am, mm_noon, mm_3pm),\n               names_to = \"reading\", values_to = \"mm\")\nhead(april_long)\n```\n:::\n\n\nThree arguments: **which columns to stack**, what to call the column\nthat remembers where each value came from (`names_to`), and what to call\nthe column holding the values themselves (`values_to`).\n\nHere is the whole operation on two days, small enough to check by eye:\n\n![](images/pivot-longer.png){fig-alt=\"Two days of the Paris register shown wide, with one row per day and three columns mm_9am, mm_noon and mm_3pm, then the same six numbers shown long, with one row per reading and columns date, reading and mm. Coloured lines join each long row back to the day it came from.\" width=\"100%\"}\n\nSix numbers go in and six come out. **Nothing is summarised and nothing\nis dropped** — it is the same data in a different shape. Wide is usually\neasier for a person to read; long is what plotting and grouping want.\n\n**4.1** How many rows does `april` have, and how many does `april_long`?\nWhat is the relationship between the two counts? Say what **one row**\nmeans in each table.\n\n::: callout-note\n## While you are counting rows\n\nApril has 30 days and `april` has fewer. The register has gaps — days\nwhen the reading was not taken, or not published. Nothing in this lab\ndepends on them.\n:::\n\n## 4.2 — Three readings, one month\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(april_long, aes(x = date, y = mm, color = reading)) +\n  geom_point(size = 1) +\n  geom_line(linewidth = 0.6) +\n  labs(x = NULL, y = \"barometer (mm)\", color = \"Reading\",\n       title = \"Three readings a day, April 1820\")\n```\n\n::: {.cell-output-display}\n![](lab-05_files/figure-html/three-readings-1.png){width=672}\n:::\n:::\n\n\nNow that `reading` is a column, `color = reading` can map it, and\n`geom_line()` draws one line per value it finds there. ggplot adds the\nlegend by itself. In `labs()`, we specify what we want the title of this legend to be by specifying `color = ...`.\nNote that we included `geom_point()` and `geom_line()` and both, the points and the lines, got stacked on the plot together.\n\n**4.2** Describe what the three lines do. Does knowing the 9 a.m.\nreading leave you in much doubt about the noon reading?\n\n## 4.3 — The same thing as a scatterplot\n\nA time plot shows two series moving together. A **scatterplot** puts one\nagainst the other directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(register, aes(x = mm_9am, y = mm_3pm)) +\n  geom_point(alpha = 0.12, size = 0.8) +\n  geom_abline(slope = 1, intercept = 0, color = \"firebrick\") +\n  labs(x = \"9 a.m. reading (mm)\", y = \"3 p.m. reading (mm)\",\n       title = \"Every day in the register\",\n       subtitle = \"Red line: where the two readings would be exactly equal\")\n```\n\n::: {.cell-output-display}\n![](lab-05_files/figure-html/day-scatter-1.png){width=672}\n:::\n:::\n\n\nWith 3,978 points, `alpha = 0.12` makes each one faint so that crowded\nregions show up dark — the standard fix for a scatterplot with too many\npoints to see through.\nLet's look ar correlation coefficients for the tree reading times. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nregister |>\n  select(mm_9am, mm_noon, mm_3pm) |>\n  drop_na() |>\n  cor() |>\n  round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        mm_9am mm_noon mm_3pm\nmm_9am   1.000   0.991  0.969\nmm_noon  0.991   1.000  0.990\nmm_3pm   0.969   0.990  1.000\n```\n\n\n:::\n:::\n\n\n**4.3** How close to the red line do the points sit? Read the three\ncorrelations. If the 9 a.m. and 3 p.m. readings have a correlaion of 0.97, **how\nmany independent numbers does one day really give you** — three, or\ncloser to one?\n\n::: callout-warning\n## Render, commit, and push\n\nRender your document, then commit and push before moving on.\n:::\n\n## 4.4 — A third view: the change within a day\n\nLaplace did not work with the raw readings. He worked with the **change\nwithin a day** — the 9 a.m. reading minus the 3 p.m. one — because\nwhatever the weather was doing affected both readings and mostly\ncancels out of their difference.\n\nPlot that quantity over the same month:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchange_spring <- register |>\n  filter(year == 1820, month == 4) |>\n  mutate(change = mm_9am - mm_3pm)\n\nggplot(change_spring, aes(x = date, y = change)) +\n  geom_hline(yintercept = 0, color = \"grey70\") +\n  geom_line(color = \"steelblue\", linewidth = 0.6) +\n  geom_point(color = \"steelblue\", size = 1) +\n  labs(x = NULL, y = \"9 a.m. minus 3 p.m. (mm)\",\n       title = \"The within-day change, April 1820\")\n```\n\n::: {.cell-output-display}\n![](lab-05_files/figure-html/change-over-time-1.png){width=672}\n:::\n:::\n\n\n**4.4** Compare this picture with the one in 4.2 — same month. The raw readings swung about 25 mm in smooth multi-day waves.\nWhat does this one do? If you knew Tuesday's value, would you have much\nidea about Wednesday's?\n\n## 4.5 — Grouping by month\n\n`data/table_4_2.csv` holds the within-day change already averaged by\nmonth — one value for each month of each year, 1816 to 1826.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly <- read_csv(\"data/table_4_2.csv\", show_col_types = FALSE) |>\n  mutate(month = factor(month, levels = c(\"Jan.\", \"Feb.\", \"Mar.\", \"Apr.\",\n                                          \"May\", \"June\", \"July\", \"Aug.\",\n                                          \"Sept.\", \"Oct.\", \"Nov.\", \"Dec.\")))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(monthly)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 132\nColumns: 4\n$ month          <fct> Jan., Feb., Mar., Apr., May, June, July, Aug., Sept., O…\n$ month_number   <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6…\n$ year           <dbl> 1816, 1816, 1816, 1816, 1816, 1816, 1816, 1816, 1816, 1…\n$ mean_change_mm <dbl> 0.513, 0.846, 0.836, 0.894, 0.613, 0.596, 0.537, 0.951,…\n```\n\n\n:::\n:::\n\n\n**132 rows, one per month-of-a-year**, in the same long shape you made\nin 4.1: each row carries its value plus the labels saying which month\nand which year it belongs to. Printed on a page this would usually be\nlaid out as a grid, twelve months by eleven years — but in a data frame\nit is a stack of 132 rows, and that is the shape `group_by()` wants.\n\nBecause the labels are columns, you can group by **either** of them. A\n**boxplot** does exactly that: it splits the rows by a label and draws\none box per group. Each box covers the middle half of that group's\nvalues, the thick line is the median, and isolated points sit far from\nthe rest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(monthly, aes(x = month, y = mean_change_mm)) +\n  geom_boxplot() +\n  labs(x = \"month\", y = \"mean daily change (mm)\",\n       title = \"The same quantity, by month\")\n```\n\n::: {.cell-output-display}\n![](lab-05_files/figure-html/by-month-1.png){width=672}\n:::\n:::\n\n\n**4.5** Careful what this axis is measuring. It is **not** how high the\nbarometer stood — it is **how much it moved between 9 a.m. and 3 p.m.**\nA low month is one where the barometer barely shifted over the course of\na day; a high month is one where it swung further.\n\nDescribe what you see. Is there a shape across the year, and which\nmonths move most and least?\n\nThen the question that matters: **would you say the eleven observations\nin December come from the same distribution as the eleven in April?**\nNot \"are they equal\" — the eleven within December are not equal to each\nother either. The question is whether all twenty-two look like they were\ngenerated by one process, or by two different ones.\n\n## 4.6 — Now do it by year\n\nSame plot, with `year` in place of `month`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YOUR CODE HERE -- adapt the by-month plot\n```\n:::\n\n\n::: callout-tip\n## One thing will go wrong\n\n`month` arrived as a factor, so ggplot knew to treat it as twelve\nseparate groups. **`year` is stored as a number**, and on a numeric axis\n`geom_boxplot()` has no idea where one group ends and the next begins —\nit draws a single box across the whole span and warns you about a\n\"continuous x aesthetic\".\n\nWrap it: `aes(x = factor(year), ...)`. That tells ggplot the eleven\nyears are eleven labels, not points on a number line.\n:::\n\n**4.6** Describe what you see here too. Then hold the two pictures side\nby side: does one of them show a pattern that the other does not?\n\n## 4.7 — Five pictures of one register\n\nYou have now drawn the same data five ways: three readings over time,\na scatterplot of 9 a.m. against 3 p.m., the within-day change over\ntime, a boxplot by month, and a boxplot by year.\n\n**4.7** For each one, write a single sentence saying **what it shows\nthat the others cannot**. Some prompts, if you are stuck: which plots\nwould survive if the rows were shuffled into a random order? Which one\nwould you use to argue that one day gives you roughly one number rather\nthan three? Which would you use to argue that February is genuinely\ndifferent from December?\n\n# Part 5 — AI slot: ask it what \"best\" means\n\n**Commit before you start.** You did this with Mayer's method in Lab 01.\nPredict the failure before you run anything.\n\nAsk an AI tool:\n\n> *Why is the arithmetic mean the best way to combine several\n> measurements of the same quantity?*\n\n**5.1** Write your prediction first: what do you expect it to leave out?\n\n**5.2** Now read what it produced. **Does it say best *by what\nstandard*?** You spent Part 3 establishing that the question has no\nanswer until a rule is named — squared errors give the mean, absolute\nerrors the median, worst error the midrange. Check whether the response:\n\n- names a criterion at all, rather than asserting the mean is best;\n- mentions that a different criterion gives a different answer;\n- mentions the median as a rival, and says when you might prefer it.\n\n**5.3** A response can be fluent, correct in every sentence, and still\nanswer a question that has not been made well posed. Did yours do the\nunderdetermined thing you did in the opening activity — pick an answer\nwithout noticing the question was incomplete? Quote the sentence where\nit either does or does not hedge.\n\n**Commit again**, so the before-and-after is on the record.\n\n# Wrap-up\n\n::: callout-warning\n## Render, commit, push, and submit\n\nRender your document and inspect the PDF. Check that you have written\nall three predictions from the opening activity, recorded the board,\nattempted each code task, filled in the three-row table in 3.5, answered\nthe closing questions, and kept commits before and after the AI\nactivity. Errors with an explanation still count as attempts. Commit and\npush the `.qmd` and PDF, then upload that PDF to Gradescope.\n:::\n\n**Exit ticket (on paper, with your name):**\n\n1. Muddiest point.\n2. One thing you learned today.\n3. Favorite holiday.\n\n## References\n\nThe historical account follows Stigler, *The History of Statistics*,\nch. 4, pp. 139–160: \"Gauss in 1809\" and \"Reenter Laplace\" for the rules\nand who preferred which, and \"A Relative Maturity: Laplace and the Tides\nof the Atmosphere\" for Part 4, whose data is Stigler's Table 4.2\n(p. 156), sourced there to Bouvard (1827).\n",
    "supporting": [
      "lab-05_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}