{
  "hash": "768303ef364375598b789dd8c1df6d57",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 03: How many trials are enough?\"\nexecute:\n  freeze: auto\n  echo: true\n  warning: false\n  message: false\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-copy: true\neditor: \n  markdown: \n    wrap: 72\n---\n\n::: callout-important\n## Due date\n\nThis lab is due **today, by the end of class**. To be considered on\ntime:\n\n- `lab-03.qmd` committed and pushed to your GitHub repo before the exit\n  ticket\n- That same document, rendered to PDF, submitted on Gradescope\n:::\n\n# Introduction\n\nConsider the following experiment: **roll a die four times, and win if\nat least one six turns up.** Today you will build this experiment in R,\nand then ask a question: **how many times would you have to play before\nthe dice told you anything?**\n\n## Learning goals\n\nBy the end of this lab you will be able to...\n\n- **count a probability through its complement**.\n- write a simulator for an event whose **one trial contains several\n  actions**.\n- understand the difference between $N$ (the trials in one experiment)\n  and $B$ (repetitions of the whole experiment).\n- state what passing a frequency check does and does not establish about\n  a die.\n\n## Getting your repo\n\n**1 · Find the repo.** The\n[statistical-history](https://github.com/statistical-history)\norganization, the repo whose name starts with `lab-03`.\n\n**2 · Clone it.** RStudio: **File → New Project → Version Control →\nGit**, paste the SSH address, **Create Project**. You should see\n`lab-03.qmd` and `lab-03-helpers.R`.\n\n**3 · Names in the YAML**, then **Render** once before you change\nanything.\n\n::: callout-tip\n## Pull first. Yes, again.\n\nIt is your own repo and nobody else has touched it. Pull anyway — the\nhabit is the point, and the one week you skip it is the week it matters.\n:::\n\n# Part 1 — Make a guess.\n\n## Before anyone opens a laptop\n\n**Write your guess.** No computing and no looking anything up. The only\nwrong answer is a blank one.\n\n> **Guess.** Someone hands you a die and says it is fair. You are\n> allowed to roll it in blocks of four and count how often at least one\n> six turns up. **How many blocks would you want before you would be\n> willing to say the die looks honest?** One number.\n\n# Part 2 — Count it first\n\n**Goal:** get the honest probability by counting.\n\nOne trial is **four rolls of a fair die**, and a trial is a **success**\nif at least one of the four is a six.\n\nThe direct count is a nuisance: you would have to add up the cases of\nexactly one six, exactly two, exactly three, and exactly four, and it is\nvery easy to double-count. **Count the complement instead** — the trials\nwith *no* six at all.\n\nFour rolls give $6^4 = 1296$ equally likely ordered outcomes. A trial\nwith no six uses only the other five faces, so there are $5^4 = 625$ of\nthose. Everything else has at least one six:\n\n$$p_0 = 1 - \\frac{5^4}{6^4} = 1 - \\frac{625}{1296} = \\frac{671}{1296}.$$\n\nFill in a code chunk in your template to calculate and save this\nprobability.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np0_six <-NA # replace with your code\np0_six\n```\n:::\n\n\n\n\n::: callout-tip\n## Stop and answer — Part 2\n\n1.  Why is this **not** $1/6$? And why is it not $4 \\times 1/6 = 2/3$?\n    Say what each of those two wrong answers is actually the probability\n    *of*.\n2.  Suppose the game were **six** rolls instead of four. Write the\n    probability down the same way and compute it. Which direction did it\n    move, and does the complement trick still work?\n:::\n\n# Part 3 — Build the mechanism\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(digits = 7)\n\nsource(\"lab-03-helpers.R\")\n```\n:::\n\n\n::: callout-warning\n## Three of today's functions are not R\n\n`check_indicators()`, `simulate_grid()` and `plot_certainty()` were\nwritten for this course. They live in `lab-03-helpers.R`, which is the\nfile you just sourced. **Open the file** if you want to see what each\nfunction does in more details; there is an index at the top and comments\nabove each function.\n\n| Call | What it does for you | First used |\n|------------------------|------------------------|------------------------|\n| `check_indicators(x, N)` | Confirms a vector is exactly `N` zeros and ones. Prints nothing when happy | Part 3 |\n| `simulate_grid(N_values, p0, epsilon, certainty_odds, B, model_p)` | Runs a whole study at each `N` you name and stacks the results into one table | Part 5 |\n| `plot_certainty(results, certainty_odds)` | Plots one of those tables, with the target marked | Part 6 |\n\nThere is a fourth, `summarize_experiments()`, which turns a pile of\nsuccess counts into one row of that table. **You never call it** —\n`simulate_grid()` calls it for you, once per `N`. It is in the file if\nyou are curious.\n\nEverything else today is **real base R** and is documented, so `?sample`\nworks: `sample()`, `rbinom()`, `numeric()`, `seq_len()`, `any()`,\n`as.integer()`, `mean()`, `table()`, `data.frame()` and `set.seed()`.\n:::\n\n**Goal:** a function that plays the game `N` times and reports, for each\nof those `N` trials, whether it was a success.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplay_six <- function(N) {\n  outcomes <- numeric(N)\n\n  for (i in seq_len(N)) {\n    rolls <- sample(1:6, size = 4, replace = TRUE)\n    outcomes[i] <- as.integer(any(rolls == 6))\n  }\n\n  outcomes\n}\n```\n:::\n\n\nLine by line:\n\n| The code | What it does |\n|------------------------------------|------------------------------------|\n| `numeric(N)` | Makes room for `N` results before the loop starts |\n| `seq_len(N)` | The trial numbers, 1 through `N` |\n| `sample(1:6, size = 4, replace = TRUE)` | Rolls the die **four times** — one whole trial |\n| `replace = TRUE` | Rolling a 3 does not remove the 3 from the die |\n| `any(rolls == 6)` | `TRUE` if at least one of the four was a six |\n| `as.integer()` | Turns `TRUE`/`FALSE` into `1`/`0` so it can be averaged |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(20260918)\n\nsmall_run <- play_six(20)\ncheck_indicators(small_run, 20)\ntable(small_run)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsmall_run\n 0  1 \n 9 11 \n```\n\n\n:::\n\n```{.r .cell-code}\nlarge_run <- play_six(50000)\ncheck_indicators(large_run, 50000)\n\ndata.frame(\n  calculated_p0 = p0_six,\n  simulated_rate = mean(large_run),\n  difference = mean(large_run) - p0_six\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  calculated_p0 simulated_rate   difference\n1     0.5177469        0.51528 -0.002466914\n```\n\n\n:::\n:::\n\n\n`check_indicators()` prints **nothing** when it is happy. That is the\nintended output. It stops with an error if the vector is the wrong\nlength or contains something other than 0 and 1 — and note what it does\n*not* check: it has no idea whether you rolled a six-sided die or a\ntwenty-sided one.\n\n::: callout-note\n## `set.seed()` — what it does, and where it must not go\n\nR's randomness is not really random; it is a long fixed sequence, and\n`set.seed(n)` says *start reading at position `n`.* Two people who set\nthe same seed get the same rolls, which is what makes a simulation\nreproducible — and why every chunk today carries one.\n\n**Set it before a study, never inside a function.** If `set.seed()` sat\ninside `play_six()`, every trial would restart the sequence at the same\nplace and all `N` trials would come out identical. The seed above is in\nthe chunk, outside the function, which is exactly right.\n:::\n\n::: callout-tip\n## Stop and answer — Part 3\n\n1.  **Which line makes a new trial start afresh (runs a new\n    experiment of rolling a die 4 times)?** Point at it.\n2.  Suppose instead you rolled the die 200 times in one long sequence\n    and slid a four-roll window along it — rolls 1–4, then 2–5, then\n    3–6. That also gives you \"trials.\" **Why are those not\n    independent?**\n3.  What does `calculated_p0` tell us and what does `simulated_rate`\n    tell us? How are the two different?\n:::\n\n# Part 4 — What we are actually going to do\n\n**Goal:** before choosing any numbers, get the whole procedure straight.\nEverything after this is just running it.\n\nPart 3 gave you one experiment, `play_six(N)`, that plays the game `N`\ntimes and `mean()` turns successes of each game into a single\nproportion. The question this lab exists to answer is what should `N` be\nand what to *do* with that number when someone hands you a die and says\nit is fair.\n\nHere is the procedure, start to finish.\n\n**· The claim.** Someone says the die is fair. **If they are right**,\none trial — four rolls, looking for at least one six — succeeds with\nchance $p_0 = 0.5177$. That is the number you counted in Part 2, and it\nis the only thing the claim buys us.\n\n**· What \"chance** $0.5177$\" actually promises. Not that an experiment\nwith a fixed `N` will give you $0.5177$. It promises that as you keep\nplaying, the proportion of trials that succeed settles near $0.5177$.\nYou already saw this in Part 3: 50,000 trials gave **0.5153**, close to\nthe counted value but not equal to it.\n\n**· One experiment gives one number.** Play $N$ trials, count $m$\nsuccesses, and you have $\\widehat p = m/N$. **Run it again and you get a\ndifferent one** — different rolls, different count. That is the whole\ndifficulty. You are trying to judge a fixed die using a number that\nmoves.\n\n**· So we allow a tolerance.** How far may $\\widehat p$ sit from $p_0$\nbefore we object? Call that distance $\\epsilon$. The interval\n\n$$[\\,p_0 - \\epsilon,\\; p_0 + \\epsilon\\,]$$\n\nis the **acceptance band**, and one experiment **passes the check** if\nits $\\widehat p$ lands inside it. That phrase — *passes the check* — is\nwhat the rest of the lab is about.\n\n**· And we set a standard.** Because $\\widehat p$ moves, an honest die\nwill sometimes miss the band by bad luck. We want that to be rare. So we demand: **an honest die must\npass at least** $c/(c+1)$ of the time.\n\n**· What we are actually looking for.** Every number here is computed\n**assuming the die is fair** — $p_0 = 0.5177$ is what a fair die gives,\nand the band is drawn around it. So the goal, stated as something we can\naim at:\n\n> **Find an** $N$ big enough that a fair die almost never lands outside\n> the band.\n\nTurn that around and you have the reason anyone would want such an $N$.\nIf at that size a fair die falls outside only once in a hundred tries,\nthen **someone who runs a single experiment and lands outside has just\nseen something that rarely happens to fair dice.** That is worth\nflagging. It is a result you would not shrug at.\n\nThat is the whole use of $N$: **the experiment size at which landing\noutside the band stops being ordinary and starts being worth a second\nlook.** Too small an $N$ and honest dice fall outside constantly, so the\nflag means nothing.\n\nWe find it by simulation, because there we set the truth ourselves. Play\nthe whole experiment $B$ times **from a die we have deliberately made\nfair**, and count how many passed. That proportion estimates\n\n$$q_N = P\\big(\\,|\\widehat p - p_0| \\le \\epsilon\\,\\big),$$\n\nand we want $q_N \\ge c/(c+1)$ — equivalently, **the chance of landing\noutside is at most** $1/(c+1)$, which for $c = 99$ is one in a hundred.\n\n::: callout-warning\n## A threshold for surprise, not a verdict\nLanding outside the band is **unlikely if the die is fair.** That is a\nstatement about fair dice. It is **not** the same as \"the die is\nprobably unfair,\" and the two come apart in a way that matters. **The debrief pulls them\napart.**\n\nFor now: you are building a threshold for *surprise*, not a verdict.\n:::\n\n::: callout-important\n## Two numbers, two jobs — this is the distinction the whole lab turns on\n\n|   | What it is | What it controls |\n|------------------------|------------------------|------------------------|\n| $N$ | trials inside **one** experiment | how much $\\widehat p$ bounces around. Bigger $N$, steadier $\\widehat p$ |\n| $B$ | how many **whole experiments** we simulate | how precisely we know $q_N$. Bigger $B$, sharper estimate |\n\n$N$ is a fact about the *study someone would actually run*. $B$ exists\nonly because we are using a simulation to determine $N$. \n:::\n\n## Now the two choices\n\nNeither has a correct answer. Both are ours to make, and the debrief comes\nback to how much they were doing.\n\n| Choice | What it means | Ours in this Lab |\n|------------------------|------------------------|------------------------|\n| **Tolerance** $\\epsilon$ | How far $\\widehat p$ may sit from $p_0$ and still pass | $p_0/5$ — a 20% relative discrepancy |\n| **Certainty odds** $c:1$ | How often an honest die must pass | $99:1$, i.e. probability $99/100$ |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nepsilon_six <- p0_six / 5\nc_odds_six <- 99\ntarget_six <- c_odds_six / (c_odds_six + 1)\n\ndata.frame(\n  p0 = p0_six,\n  epsilon = epsilon_six,\n  band_lower = p0_six - epsilon_six,\n  band_upper = p0_six + epsilon_six,\n  certainty_odds = c_odds_six,\n  target_probability = target_six\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         p0   epsilon band_lower band_upper certainty_odds target_probability\n1 0.5177469 0.1035494  0.4141975  0.6212963             99               0.99\n```\n\n\n:::\n:::\n\n\n`band_lower` and `band_upper` are the two ends of the acceptance band.\n**An experiment passes if its** $\\widehat p$ falls between them,\nendpoints included.\n\n::: callout-important\n## Making $\\epsilon$ a *fraction* of $p_0$ is itself a decision\n\nWe could have picked a flat number — 0.02, say, the way Bernoulli did\nfor his urn. Writing it as $p_0/5$ instead means the tolerance **scales\nwith the event**: a common event gets a wide band and a rare one gets a\nnarrow band.\n\nThat choice is doing more work than it looks like, and HW 02 makes you\nfeel it. Hold on to this one; the debrief comes back to it.\n:::\n\n::: callout-tip\n## Stop and answer — Part 4\n\n1.  Our band is $[0.414, 0.621]$ — **more than a fifth of the whole\n    probability scale wide.** Name a use for this check where that width\n    is fine, and one where it plainly is not.\n2.  A die is loaded so that a six comes up with chance $1/5$ instead of\n    $1/6$. That makes this event's probability $1 - (4/5)^4$. \n    Add a code chunk to calculate this value. Does this value fall inside the band we chose?\n:::\n\n# Part 5 — Run it once, for a fixed $N$.\n\n**Goal:** see what the helper's table actually reports, at a large $N$.\n\nPart 3 ran 50,000 trials. Let us keep that size, and run the\nhonest-model study described above: simulate $B = 10{,}000$ whole\nexperiments of 50,000 trials each, and count how many pass.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(61000)\n\nsix_fixed <- simulate_grid(\n  N_values = 50000,\n  p0 = p0_six,\n  epsilon = epsilon_six,\n  certainty_odds = c_odds_six,\n  B = 10000\n)\n\nsix_fixed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      N     B inside outside q_hat odds_hat   lower95 upper95 assessment\n1 50000 10000  10000       0     1       NA 0.9996312       1      meets\n```\n\n\n:::\n:::\n\n\nAll 10,000 experiments passed. At this size $\\widehat p$ has essentially nowhere to go, so\nthat is no surprise.\n\n| Column | What it is claiming | Here |\n|---|---|---|\n| `inside`, `outside` | How many of the $B$ experiments passed and failed. They add to $B$ | 10,000 and 0 |\n| `q_hat` | `inside / B` — the estimated chance that a whole experiment passes | 1.0000 |\n| `odds_hat` | `inside / outside`. **`NA` means no failures were seen**, not that the odds are infinite | `NA` |\n| `lower95`, `upper95` | How much to trust `q_hat`, given how many experiments you ran — see below | 0.99963 to 1 |\n| `assessment` | Those two, compared against the $99/100$ target | `meets` |\n\n## How to read the simulation uncertainty\n\nThe helpers report `lower95` and `upper95`, a 95% Monte Carlo interval for $q_N$. You do not need to understand how it is built and what it means beyond that it describes\nthe precision of your simulation estimate, and it is a separate thing from your chosen\n$99:1$ requirement.\n\n| `assessment` | Interpretation at this tested $N$ |\n|---|---|\n| `meets` | The whole interval is at or above $c/(c+1)$ |\n| `below` | The whole interval is below $c/(c+1)$ |\n| `unresolved` | The interval straddles the target — this simulation is not precise enough to decide |\n\n**If `assessment` says `unresolved`, it means $B$ is not high enough to make a decision about\n$q_N$.** Not that the die failed, and not that this $N$ is wrong — only that this many\nexperiments cannot tell which side of the target the truth is on. The fix is more experiments,\nnot more trials. \n\n\n::: callout-tip\n## Stop and answer — Part 5\n\n1.  `q_hat` came back as exactly 1. **How many of the 10,000 experiments had their\n    $\\widehat p$ land inside the band?** And what does that have to do with `odds_hat`\n    printing `NA`?\n2.  Imagine you have a slider that controls $\\epsilon$, keeping everything else the same. Suppose you drag it towards zero, thus, making the band **narrower** around the same $p_0$. **Would `q_hat` go up or down as the slider for epsilon gets closer to zero?**\n:::\n\n# Part 6 — Can we get away with less?\n\n**Goal:** $N = 50{,}000$ works, but it is 200,000 individual rolls and\nnobody is doing that at a table. We will now test a variety of different values of $N$ and try to find the smallest experiment size that\nstill clears the standard.\n\n::: callout-note\n## What we are really searching for\nRemember, we are trying to find $N$ such that if we run the experiment and calculate $\\hat p$, it would land within $\\epsilon$ of the truth $p_0$ with probability $\\frac{c}{c+1}$.  \n:::\nWe start by checking a wide variety of values of $N$ and assess them with $B=10,000$ repetitions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(61001)\n\nsix_N <- c(25, 50, 100, 150, 200, 250, 300, 400, 500, 750, 1000)\n\nsix_pilot <- simulate_grid(\n  N_values = six_N,\n  p0 = p0_six,\n  epsilon = epsilon_six,\n  certainty_odds = c_odds_six,\n  B = 10000\n)\n\nsix_pilot\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      N     B inside outside  q_hat    odds_hat   lower95   upper95 assessment\n1    25 10000   6846    3154 0.6846    2.170577 0.6753898 0.6937026      below\n2    50 10000   8813    1187 0.8813    7.424600 0.8747995 0.8875775      below\n3   100 10000   9657     343 0.9657   28.154519 0.9619446 0.9691809      below\n4   150 10000   9889     111 0.9889   89.090090 0.9866479 0.9908601 unresolved\n5   200 10000   9968      32 0.9968  311.500000 0.9954855 0.9978102      meets\n6   250 10000   9987      13 0.9987  768.230769 0.9977780 0.9993076      meets\n7   300 10000   9998       2 0.9998 4999.000000 0.9992777 0.9999758      meets\n8   400 10000  10000       0 1.0000          NA 0.9996312 1.0000000      meets\n9   500 10000  10000       0 1.0000          NA 0.9996312 1.0000000      meets\n10  750 10000  10000       0 1.0000          NA 0.9996312 1.0000000      meets\n11 1000 10000  10000       0 1.0000          NA 0.9996312 1.0000000      meets\n```\n\n\n:::\n:::\n\n\nWe now plot estimated $\\hat q_N$ for each $N$ we tested. The dashed horizontal line corresponds to our goal of $q_N = 0.99$. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_certainty(six_pilot, certainty_odds = c_odds_six)\n```\n\n::: {.cell-output-display}\n![](lab-03_files/figure-html/six-pilot-plot-1.png){width=672}\n:::\n:::\n\n\n**Read down the `assessment` column, not the `q_hat` column.** Three\nrows matter:\n\n| $N$ | `q_hat` | `assessment` | What it tells you |\n|------------------:|------------------:|-----------------|-----------------|\n| 100 | 0.9657 | `below` | Too small. The whole interval is under 0.99 |\n| 150 | 0.9889 | `unresolved` | Above 0.99 as a point estimate, **and still not callable** — the interval crosses the line |\n| 200 | 0.9968 | `meets` | Clears it, interval and all |\n\nSo the transition is somewhere between 100 and 200. We have looked at 150 but did not use sufficiently large $B$ to draw conclusions. Everything from 250 up also passes, but those are\nmore expensive and tell us nothing new. Zoom in on the window that is\nactually in doubt.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(61002)\n\nsix_refined_N <- c(105, 115, 125, 135, 145, 155, 165, 175, 185, 195)\n\nsix_refined <- simulate_grid(\n  N_values = six_refined_N,\n  p0 = p0_six,\n  epsilon = epsilon_six,\n  certainty_odds = c_odds_six,\n  B = 10000\n)\n\nsix_refined\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     N     B inside outside  q_hat  odds_hat   lower95   upper95 assessment\n1  105 10000   9654     346 0.9654  27.90173 0.9616297 0.9688960      below\n2  115 10000   9754     246 0.9754  39.65041 0.9721719 0.9783470      below\n3  125 10000   9790     210 0.9790  46.61905 0.9759962 0.9817201      below\n4  135 10000   9840     160 0.9840  61.50000 0.9813449 0.9863675      below\n5  145 10000   9868     132 0.9868  74.75758 0.9843657 0.9889443      below\n6  155 10000   9884     116 0.9884  85.20690 0.9861030 0.9904055 unresolved\n7  165 10000   9911      89 0.9911 111.35955 0.9890590 0.9928466 unresolved\n8  175 10000   9945      55 0.9945 180.81818 0.9928469 0.9958540      meets\n9  185 10000   9949      51 0.9949 195.07843 0.9932998 0.9962004      meets\n10 195 10000   9967      33 0.9967 302.03030 0.9953687 0.9977274      meets\n```\n\n\n:::\n:::\n\n\n145 and lower are `below`. 155 and 165 are still `unresolved`; 175 and up all read `meets`. **Notice what\nthat does and does not establish.** It says 175 passed at this $B$, on\nthis seed. It does not say 174 fails, and it does not say 175 is the\nsmallest possible — we tested ten numbers out of a hundred.\n\n\n::: callout-tip\n## Stop and answer — Part 6\n\n1.  In the pilot, between which two values of $N$ does `assessment` stop\n    saying `below`?\n2.  155 comes back `unresolved` at the same $B$ as before. **What one change would\n    settle if $155$ is large enough?**\n3.  $N$ and $B$ both make things \"more accurate,\" but not the same\n    thing. One of them sharpens our estimate of $\\widehat p$; the other\n    sharpens our estimate of $P(\\widehat p \\text{ lands in the band})$.\n    **Which does which** ?\n:::\n\n# Part 7 — Confirm it\n\n**Goal:** one fresh study, at a new seed and ten times the experiments, on the values the\nsearch could not settle.\n\n## Which values are worth re-testing, and why $B$ jumps\n\nThe refinement left **155 and 165 `unresolved`** and put the first `meets` at **175**. Those\nthree are the ones to confirm — and notice **it is not the `below` rows that are worth\nre-running.** 105 through 145 came back with their whole intervals under the target; running\nthem again at ten times the cost would only say `below` in more decimal places.\n\n**The undecided ones are different.** `unresolved` means the study could not tell which side\nof the target the truth was on. Look harder and it might come back `meets` — **which would\nhand you a smaller, cheaper answer than 175.** That is the entire reason to spend the extra\nexperiments.\n\nAnd $B$ goes from 10,000 to 100,000 because our target is 0.99: we are trying to measure a\nfailure rate of about one in a hundred, and 10,000 experiments expect only about 100\nfailures. Ten times the experiments, ten times the resolution — **on $q_N$, not on the die.**\n\n::: callout-important\n## Fix your values *before* you run this\n\nA confirmation is only worth something if you chose what to confirm beforehand. Write 155,\n165 and 175 down. Then run the chunk **once**.\n\n**Rerunning with new seeds until something passes is not a confirmation** — it is a search\nwearing a confirmation's clothes, and it makes the number meaningless.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(61003)\n\nsix_confirm_N <- c(155, 165, 175)\n\nsix_confirmation <- simulate_grid(\n  N_values = six_confirm_N,\n  p0 = p0_six,\n  epsilon = epsilon_six,\n  certainty_odds = c_odds_six,\n  B = 100000\n)\n\nsix_confirmation\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    N      B inside outside   q_hat odds_hat   lower95   upper95 assessment\n1 155 100000  99020     980 0.99020 101.0408 0.9895700 0.9908013 unresolved\n2 165 100000  99203     797 0.99203 124.4705 0.9914594 0.9925718      meets\n3 175 100000  99378     622 0.99378 159.7717 0.9932731 0.9942579      meets\n```\n\n\n:::\n:::\n\n\n**165 resolved.** At $B = 10{,}000$ it was undecided; at $B = 100{,}000$ it reads `meets`, at\n$\\widehat q = 0.99203$ with the whole interval above the target. **So the answer improves from\n175 to 165** — the extra experiments bought a smaller $N$, which is exactly what we hoped for\nand why the smaller values were worth testing at all.\n\n**155 did not resolve.** It is still `unresolved` at ten times the effort, sitting at\n$0.99020$ with its interval straddling 0.99.\n\n::: callout-warning\n## Not every `unresolved` is a shortage of experiments\n\n165 was undecided because $B$ was too small — look harder and it settles. **155 is a\ndifferent animal.** Its true pass rate sits almost exactly on 0.99, so no affordable number\nof experiments will ever put it cleanly on one side. More $B$ would not help.\n\n**That is a real and reportable result**, not a failure. The honest statement is: *165 is the\nsmallest tested size we can support; 155 we cannot resolve, and would need far more than\n100,000 experiments to try.*\n:::\n\n::: callout-tip\n## Stop and answer — Part 7\n\n1.  The refinement said 175 and the confirmation says 165. **Which is the better answer, and\n    what did the extra experiments actually buy you?**\n2.  105 through 145 all came back `below` in the refinement, and we did **not** re-run them\n    here. **Why not?** What would testing them again have told you?\n:::\n\n# Part 8 — Debrief\n\n**Back together as a room.**\n\n## One — you found $N$. Now what?\n\n::: callout-important\n## The question Part 4 left open\n\nEverything today assumed the die is fair. So the study cannot *tell* you\na die is fair — it only found how big an experiment a **fair** die\nneeds.\n\nNow hand that $N$ to someone holding a real die they know nothing about.\nThey roll $N$ trials and get one $\\widehat p$.\n:::\n\nSuppose their $\\widehat p$ lands **outside** the band. You built the check so that a fair\ndie stays inside 99 times out of 100. **So what has just happened, and what should they\nthink?**\n\nSay it carefully — and then say what they should think if it lands **inside** instead.\n\n## Two — which way does $N$ move?\n\nEverything today held $\\epsilon$, $c$ and $p_0$ fixed and hunted for $N$. Now turn the\nhandle the other way: change one of those three and ask **what $N$ would have to do to keep\nthe same standard.**\n\n**Say bigger, smaller, or no change — and why.**\n\n**(a)** We make $\\epsilon$ **smaller** — a narrower band, everything else the same.\n\n**(b)** We make $c$ **larger** — say $999:1$ instead of $99:1$.\n\n# Part 9 — AI slot: the Decision Audit\n\nOpen a fresh chat and give it exactly this, and nothing else:\n\n> *I roll a die 7 times. What is the probability I get at least one\n> six?*\n\nThat is Part 2's question with a 7 in place of the 4, so **you can check\nits arithmetic yourself** — and it will almost certainly get the\narithmetic right. **The answer is not what we are auditing.**\n\nYour deliverable is a list of **everything it had to decide before it\ncould answer at all**, none of which you told it.\n\n You can start here.\n\n| It had to assume something about… | Ask yourself |\n|------------------------------------|------------------------------------|\n| **How many sides** the die has | You never said six. Did it say it was assuming six, or just use it? |\n| **Whether the die is fair** | Did it ask? Did it flag it? |\n| **Whether the rolls are independent** | How does it combine probabilities from different rolls|\n| **What you wanted it for** | A homework answer, a bet, a dice-tower audit? The number is the same; what you should *do* with it is not |\n\n\n**Hand in** a list of things it had to decide on and **which of those it told you about**.\n\n## Exit ticket\n\n1.  Muddiest point?\n2.  One thing you've learned today.\n3.  What is your home town?\n\nMake sure your name is on it as this is how attendance is taken.\n",
    "supporting": [
      "lab-03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}